### ISSUE TITLE
How to view data on python

### ISSUE THREAD

**Issue by GiovanniVignoli95** [hydrogo/rainymotion#11]
Hi Georgy,
I have 3 questions
I want to see the values in file "data.h5", but how can I view data on python? I can't see all the data:

import h5py
f = h5py.File("./rainymotion-master/rainymotion-master/data/data.h5", mode="r")
print(f['201605291650'][:])

and I see:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

2) what is the file "eval_dict.npy"?

3)With this script:

from rainymotion.models import Dense
model = Dense()
model.input_data = open("./rainymotion-master/rainymotion-master/data/data.h5")
nowcasts = model.run()

I get a file without values. Where is my error?

Thanks you
Giovanni

**Comment by ElmerJeanpierreLopez** [comment]
Hi,

I'm not Georgy, but I'm trying to answer your questions. 
1) Data from radars usually are array-like with two dimensions. So it can be represented in a grid. 
In your case you can try: 

import h5py
import matplotlib.pyplot as plt

f = h5py.File("./rainymotion-master/rainymotion-master/data/data.h5", mode="r")
data = f['201605291650'][:]
print(f['201605291650'][:]) # Array is too large, so it won't display totally

print(f.keys())          # See keys on the file
plt.imshow(data.astype(float)) 
plt.colorbar()

2) It's just another file. Contain radar data in a format that it could be read by the numpy library. 

import numpy as np
evaluation = np.load("./rainymotion-master/rainymotion-master/data/eval_dict.npy", allow_pickle=True)

3) I'm surprised because you don't get an error. So you need to pass the array-like, and you give an object. Read the documentation of the function to more details.

**Comment by hydrogo** [comment]
Hi @GiovanniVignoli95 and @ElmerJeanpierreLopez,
First, I would like to thank you in your interest in `rainymotion`. Many additional thanks to @ElmerJeanpierreLopez for your help answering the questions about `rainymotion`.

Actually, I do not know what to add to the answer provided by @ElmerJeanpierreLopez. Basically, you have to feed a 2D radar data to rainymotion, and then the model does its job. You can find some examples using German radar data in the documentation.

I am sorry for late answers as I am pretty busy with papers, reviews, and grant reports this time of the year :-(

Best,
Georgy

**Comment by GiovanniVignoli95** [comment]
Ok thanks you.
But I have to feed a 2D o 3D array to rainymotion? data.h5 is in 3D, not in 2D
Can you write an example to view or to save the array in output?

giovanni

**Comment by ElmerJeanpierreLopez** [comment]
You need to feed with 3D array (frames, x_samples, y_samples). Be careful that your data shouldn't contain NaN values, because if it has you'll obtain a matrix filled with zeros. Data h5 is an object of h5py library not an array exactly. Then you obtain the predicted output values using:

nowcasts = model.run()

For plotting, you can use Matplotlib library:

import matplotlib.pyplot as plt
fig = plt.figure()
plt.pcolormesh(nowcast[0, :, :])         # Change the number according what prediction do you want
fig.savefig('Radar image.jpg')
With this you can obtain images of your data. If you want to save your data use an auxiliar library

import numpy as np
np.save('Data.npy', nowcasts)

But data is useless without metadata. It's a good idea use a format like h5py or netcdf files instead in order to add the metadata. Also these formats admit compression. 
 
Last, a final thoughts. It seems that you are not very familiar with most common libraries of Python such a numpy or matplotlib. Maybe I'm wrong, but if it's the case is a good idea for you to learn a bit about it.

**Comment by GiovanniVignoli95** [comment]
Thanks you for everything! 

I know I'm not a python expert. My problem is that I need the output matrix to insert it into another model.
So if I insert a 3D matrix (.npy, h5, HDF5 ....) it would be enough to have it outgoing, but I can't extract it from nocast = model.run ()

I'll try again!

Thanks
Giovanni
