### ISSUE TITLE
Is this project available for GPU acceleration?

### ISSUE THREAD

**Issue by scut-salmon** [hydrogo/rainymotion#2]
Hi,
I have successfully used this module to predict my radar map, but I found that it runs really slow, how can I accelerate it? Is this module available for the GPU acceleration?
Any suggestion would be appreciated
Thanks,
Zhang

**Comment by hydrogo** [comment]
Dear Zhang,

Thank you for your effort in testing `rainymotion`. Yes, you are right that `rainymotion` is slow and we will tackle this problem in next releases by implementing parallel computing using dask or multiprocessing (will be one order times faster). 

Unfortunately, I have no idea how to develop a source code for computation on GPU.

The last, but not least. `rainymotion` sacrifices speed for the sake of quality (see the latest comparison with `pysteps` here: https://twitter.com/hydrogo89/status/1032164649737879553).

Best, 
Georgy

**Comment by scut-salmon** [comment]
@hydrogo Yes, multi process is a solution, Still hope there's a GPU computation, which is more convenient :)

Seems that the model Dense() and DenseRotation() is the most time consuming and they performs best, while the radar map turn blur when the lead_steps was set to 30-40, especially for DenseRotation(). Is there any way to solve it?

Thanks,
Zhang

**Comment by hydrogo** [comment]
@scut-salmon There is no way to solve this issue with blurring on longer lead times predictions, because of for every lead time we use bilinear extrapolation as a tool for performing advection which unfortunately leads to numerical diffusion. For DenseRotation it can be more apparent especially for modeling events without a strong rotational component. 

I do not see any problem in blurring because of I also find it quite natural -- our confidence in predictions is decreasing for longer time steps then uncertainty increasing (and reflects in blur effect).

In literature, you can also find that the 2-3 hours is a limit of predictability for data-driven nowcasting models. In my experience, you can only rely on the first-hour predictions.
